/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo2.RedFlix.Vistas;

import com.grupo2.RedFlix.Modelos.Entidades.Pelicula;
import com.grupo2.RedFlix.Modelos.Entidades.Serie;
import com.grupo2.RedFlix.Modelos.Entidades.Usuario;
import com.grupo2.RedFlix.Modelos.Repositorios.PeliculaRepositorio;
import com.grupo2.RedFlix.Modelos.Repositorios.SerieRepositorio;
import com.grupo2.RedFlix.Modelos.Repositorios.UsuarioRepositorio;
import com.grupo2.RedFlix.RedFlixApplication;
import com.grupo2.RedFlix.Utilidades.SpringContext;
import java.util.Optional;

/**
 *
 * @author felip
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private SerieRepositorio serieRepositorio;
    private PeliculaRepositorio peliculaRepositorio;
    private UsuarioRepositorio usuarioRepositorio;
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        String args[] = {};
        RedFlixApplication.SpringRunner(args);
        serieRepositorio = SpringContext.getBean(SerieRepositorio.class);
        peliculaRepositorio = SpringContext.getBean(PeliculaRepositorio.class);
        usuarioRepositorio= SpringContext.getBean(UsuarioRepositorio.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        botonAgregar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        labelAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedFlix");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Categoría:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Buscador:");

        comboBoxCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Series", "Peliculas", "Usuarios" }));

        botonAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAlerta)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonAgregar))
                                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(labelAlerta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        if(campoBuscar.getText().isEmpty())
        {
            labelAlerta.setText("Ingrese un dato válido");
        }
        else
        {
            String id = campoBuscar.getText();
            switch((String) comboBoxCategoria.getSelectedItem())
            {
                case "Series":
                    Optional<Serie> serie = serieRepositorio.findById(id);
                    if(serie.isPresent())
                    {
                        new VentanaSerie(id, false).setVisible(true);
                        labelAlerta.setText("");
                    }
                    else
                    {
                        labelAlerta.setText("Serie no encontrada");
                    }
                    break;
                    
                case "Peliculas":
                    Optional<Pelicula> pelicula = peliculaRepositorio.findById(id);
                    if(pelicula.isPresent())
                    {
                        new VentanaPelicula(id, false).setVisible(true);
                        labelAlerta.setText("");
                    }
                    else
                    {
                        labelAlerta.setText("Pelicula no encontrada");
                    }
                    break;
                case "Usuarios":
                    Optional<Usuario> usuario = usuarioRepositorio.findById(id);
                    if(usuario.isPresent())
                    {
                        new VentanaUsuario(id, false).setVisible(true);
                        labelAlerta.setText("");
                    }
                    else
                    {
                        labelAlerta.setText("Usuario no encontrado");
                    }
                    break;
            }
        }
        
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        if(campoBuscar.getText().isEmpty())
        {
            labelAlerta.setText("Digite el título que desea agregar");
        }
        else
        {
            String id = campoBuscar.getText();
            switch((String) comboBoxCategoria.getSelectedItem())
            {
                case "Series":
                    Optional<Serie> serie = serieRepositorio.findById(id);
                    if(serie.isPresent())
                    {
                        labelAlerta.setText("El titulo ya existe");
                    }
                    else
                    {
                        new VentanaSerie(id, true).setVisible(true);
                        labelAlerta.setText("");
                    }
                    break;
                    
                case "Peliculas":
                    Optional<Pelicula> pelicula = peliculaRepositorio.findById(id);
                    if(pelicula.isPresent())
                    {
                        labelAlerta.setText("Pelicula ya existe");
                    }
                    else
                    {
                        new VentanaPelicula(id, true).setVisible(true);
                        labelAlerta.setText("");
                    }
                    break;
                case "Usuarios":
                    Optional<Usuario> usuario = usuarioRepositorio.findById(id);
                    if(usuario.isPresent())
                    {
                        labelAlerta.setText("Usuario ya existe");
                    }
                    else
                    {
                        new VentanaUsuario(id, true).setVisible(true);
                        labelAlerta.setText("");
                    }
                    break;
                    
            }
        }
    }//GEN-LAST:event_botonAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAlerta;
    // End of variables declaration//GEN-END:variables
}
