/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo2.RedFlix.Vistas;

import com.grupo2.RedFlix.Modelos.Entidades.Serie;
import com.grupo2.RedFlix.Modelos.Repositorios.SerieRepositorio;
import com.grupo2.RedFlix.Utilidades.SpringContext;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class VentanaSerie extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSerie
     */
    private String titulo;
    private SerieRepositorio serieRepositorio;
    private Serie serie;
    
    public VentanaSerie(String titulo, boolean ventanaAgregar) {
        initComponents();
        serieRepositorio = SpringContext.getBean(SerieRepositorio.class);
        this.titulo = titulo;
        actualizarVentana(ventanaAgregar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTituloSerie = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerTemporadasSerie = new javax.swing.JSpinner();
        spinnerEpisodiosSerie = new javax.swing.JSpinner();
        botonActualizarSerie = new javax.swing.JButton();
        botonEliminarSerie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD Serie");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTituloSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloSerie.setText("Título");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Número de temporadas:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Número de episodios:");

        spinnerTemporadasSerie.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnerEpisodiosSerie.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        botonActualizarSerie.setText("Actualizar");
        botonActualizarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarSerieActionPerformed(evt);
            }
        });

        botonEliminarSerie.setText("Eliminar");
        botonEliminarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(labelTituloSerie))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addComponent(botonActualizarSerie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEliminarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerEpisodiosSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(33, 33, 33)
                                    .addComponent(spinnerTemporadasSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelTituloSerie)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerTemporadasSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerEpisodiosSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizarSerie)
                    .addComponent(botonEliminarSerie))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarSerieActionPerformed
        // TODO add your handling code here:
        serie.setSerieEpisodios((Integer) spinnerEpisodiosSerie.getValue());
        serie.setSerieTemporadas((Integer) spinnerTemporadasSerie.getValue());
        serieRepositorio.save(serie);
        if (botonActualizarSerie.getText().equals("Crear")){
            JOptionPane.showMessageDialog(null,"Se creó correctamente la serie");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Se actualizó correctamente la serie");
            this.dispose();
        }
        
    }//GEN-LAST:event_botonActualizarSerieActionPerformed

    private void botonEliminarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSerieActionPerformed
        // TODO add your handling code here:
        serieRepositorio.deleteById(titulo);
        JOptionPane.showMessageDialog(null, "Se eliminó correctamente");
        this.dispose();
    }//GEN-LAST:event_botonEliminarSerieActionPerformed
    
    private void actualizarVentana(boolean ventanaAgregar)
    {
        serie = new Serie();
        labelTituloSerie.setText(titulo);
        if (ventanaAgregar){
            serie.setSerieTitulo(titulo);
            botonActualizarSerie.setText("Crear");
            botonEliminarSerie.setVisible(false);
        }else{
            serie = (Serie) serieRepositorio.findById(titulo).get();
            spinnerEpisodiosSerie.setValue(serie.getSerieEpisodios());
            spinnerTemporadasSerie.setValue(serie.getSerieTemporadas());
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarSerie;
    private javax.swing.JButton botonEliminarSerie;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTituloSerie;
    private javax.swing.JSpinner spinnerEpisodiosSerie;
    private javax.swing.JSpinner spinnerTemporadasSerie;
    // End of variables declaration//GEN-END:variables
}
