/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupo2.RedFlix.Vistas;

import com.grupo2.RedFlix.Modelos.Entidades.Pelicula;
import com.grupo2.RedFlix.Modelos.Repositorios.PeliculaRepositorio;
import com.grupo2.RedFlix.Utilidades.SpringContext;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class VentanaPelicula extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPelicula
     */
    
    private String titulo;
    private PeliculaRepositorio peliculaRepositorio;
    private Pelicula pelicula;
    
    public VentanaPelicula(String titulo, boolean ventanaAgregar) {
        initComponents();
        peliculaRepositorio = SpringContext.getBean(PeliculaRepositorio.class);
        this.titulo = titulo;
        actualizarVentana(ventanaAgregar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTituloPelicula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcionPelicula = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerAnioPelicula = new javax.swing.JSpinner();
        campoDirectorPelicula = new javax.swing.JTextField();
        botonActualizarPelicula = new javax.swing.JButton();
        botonEliminarPelicula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD Pelicula");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTituloPelicula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloPelicula.setText("Título");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descripción:");

        textAreaDescripcionPelicula.setColumns(20);
        textAreaDescripcionPelicula.setRows(5);
        jScrollPane1.setViewportView(textAreaDescripcionPelicula);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Año:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Director:");

        spinnerAnioPelicula.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, null, 1));

        botonActualizarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonActualizarPelicula.setText("Actualizar");
        botonActualizarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarPeliculaActionPerformed(evt);
            }
        });

        botonEliminarPelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonEliminarPelicula.setText("Eliminar");
        botonEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTituloPelicula)
                .addGap(211, 211, 211))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerAnioPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDirectorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(botonActualizarPelicula)
                        .addGap(49, 49, 49)
                        .addComponent(botonEliminarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTituloPelicula)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDirectorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerAnioPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizarPelicula)
                    .addComponent(botonEliminarPelicula))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarPeliculaActionPerformed
        // TODO add your handling code here:
        pelicula.setPeliculaResumen(textAreaDescripcionPelicula.getText());
        pelicula.setPeliculaDirector(campoDirectorPelicula.getText());
        pelicula.setPeliculaAnio((Integer) spinnerAnioPelicula.getValue());
        peliculaRepositorio.save(pelicula);
        if (botonActualizarPelicula.getText().equals("Crear")){
            JOptionPane.showMessageDialog(null,"Se creó correctamente la serie");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Se actualizó correctamente la serie");
            this.dispose();
        }
    }//GEN-LAST:event_botonActualizarPeliculaActionPerformed

    private void botonEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPeliculaActionPerformed
        // TODO add your handling code here:
        peliculaRepositorio.deleteById(titulo);
        JOptionPane.showMessageDialog(null, "Se eliminó correctamente");
        this.dispose();
    }//GEN-LAST:event_botonEliminarPeliculaActionPerformed

    private void actualizarVentana(boolean ventanaAgregar)
    {
        pelicula = new Pelicula();
        labelTituloPelicula.setText(titulo);
        if (ventanaAgregar){
            pelicula.setPeliculaTitulo(titulo);
            botonActualizarPelicula.setText("Crear");
            botonEliminarPelicula.setVisible(false);
        }else{
            pelicula = (Pelicula) peliculaRepositorio.findById(titulo).get();
            textAreaDescripcionPelicula.setText(pelicula.getPeliculaResumen());
            campoDirectorPelicula.setText(pelicula.getPeliculaDirector());
            spinnerAnioPelicula.setValue(pelicula.getPeliculaAnio());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarPelicula;
    private javax.swing.JButton botonEliminarPelicula;
    private javax.swing.JTextField campoDirectorPelicula;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloPelicula;
    private javax.swing.JSpinner spinnerAnioPelicula;
    private javax.swing.JTextArea textAreaDescripcionPelicula;
    // End of variables declaration//GEN-END:variables
}
